// index.ts
export { default as Pagination } from './Pagination.vue'
export { default as PaginationFirst } from './First.vue'
export { default as PaginationPrev } from './Prev.vue'
export { default as PaginationNext } from './Next.vue'
export { default as PaginationLast } from './Last.vue'
export { default as PaginationPageList } from './PageList.vue'
export { default as PaginationPage } from './Page.vue'
export { default as PaginationGoToPage } from './GoToPage.vue'
export { default as PaginationPageNumber } from './PageNumber.vue'
