export { default as Table } from './Table.vue'
export { default as TableCaption } from './TableCaption.vue'
export { default as TableHeader } from './TableHeader.vue'
export { default as TableBody } from './TableBody.vue'
export { default as TableFooter } from './TableFooter.vue'
