export { default as Table } from './Table.vue'
export { default as TableCaption } from './TableCaption.vue'
export { default as TableHeader } from './TableHeader.vue'
export { default as TableBody } from './TableBody.vue'
export { default as TableFooter } from './TableFooter.vue'
export { default as TableSelectAllRows } from './TableSelectAllRows.vue'
export { default as TableSelectRow } from './TableSelectRow.vue'
