// index.ts
export { default as Pagination } from './src/Pagination.vue'
export { default as PaginationFirst } from './src/First.vue'
export { default as PaginationPrev } from './src/Prev.vue'
export { default as PaginationNext } from './src/Next.vue'
export { default as PaginationLast } from './src/Last.vue'
export { default as PaginationPageList } from './src/PageList.vue'
export { default as PaginationPage } from './src/Page.vue'
export { default as PaginationGoToPage } from './src/GoToPage.vue'
export { default as PaginationPageNumber } from './src/PageNumber.vue'
